### ISSUE TITLE
2.10 - Can't move/copy/delete or files.

### ISSUE THREAD

**Issue by jordaninthesky** [joel16/NX-Shell#63] opened 2019-10-01 00:23 UTC
Nothing happens.  No error.  Confirmation prompt pops, but nothing changes in the file-structure.  Renaming works for me, though.

I am on latest Atmosphere and FW versions, to date.  2.00 still works for me.

**Comment by joel16** [comment] 2019-10-01 01:37
Thanks for letting me know! However, this is a duplicate of https://github.com/joel16/NX-Shell/issues/62. Please follow that issue until a fix is pushed.

**Closed as completed by joel16** 2019-10-01 01:37 UTC

**Comment by jordaninthesky** [comment] 2019-10-01 02:06
Oops, my mistake.  Saw the screenshot and thought it was about renaming.
