### ISSUE TITLE
NX-Shell Crashes when last open directory is a TitleID

### ISSUE THREAD

**Issue by ursineasylum** [joel16/NX-Shell#82] opened 2020-07-15 03:56 UTC
Version: 3.0.1

Repro:
- Launch NX-Shell
- Navigate to any folder under `/atmosphere/contents/`, ex `/atmosphere/contents/01007EF00011E000`
- Exit NX-Shell
- Relaunch NX-Shell

Expected:
- NX-Shell launches

Actual:
- NX-Shell crashes with an unexpected error in Application mode, or crashes the console in Applet mode.

If you then navigate to `/switch/NX-Shell/config.json` and modify the "last_dir" to, ex, `/atmosphere/contents` and save, NX-Shell will launch properly as expected. 

This issue will *not* occur if last_dir is a subdirectory of the title id, ex `/atmosphere/contents/01007EF00011E00/romfs`

**Comment by joel16** [comment] 2020-08-01 16:03
Sorry for being very late on this. Just tested this on my device and can indeed confirm this is also happening here. I'm going to attempt and fix this.

**Comment by joel16** [comment] 2020-08-01 16:15
Alright I see what the problem is, and it should be fixed with the next release.

**Closed as completed by joel16** 2020-08-01 16:15 UTC
